FROM registry.access.redhat.com/ubi9/openjdk-17:1.15-1.1686736679

#USER root
#RUN microdnf install -y git vim-enhanced && \
#    microdnf clean all


#RUN git --version
RUN mkdir test-fips
WORKDIR /home/default/test-fips
RUN pwd
COPY tls tls
COPY src src
COPY pom.xml .
COPY run.sh .
RUN mvn clean install

CMD [ "bash" ]